version: '3.7'
services:
    
  postgres:
    container_name: database
    image: postgres:12.3-alpine
    ports:
      - '5432'
    networks:
      - default

  interview_api:
    container_name: backend
    build: ./backend
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - '8000:9090'
    networks:
      - default
    links:
      - postgres

networks:
  default:
    driver: bridge
  